### ISSUE TITLE
Latest version number and proper failure is not guaranteed

### ISSUE THREAD

**Issue by zsoltion** [AnimMouse/setup-rclone#1]
One of our workflow run failed with the following error:

> [ERROR] CUID#7 - Download aborted. URI=https://github.com/rclone/rclone/releases/download/null/rclone-null-osx-amd64.zip
>   Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://github.com/rclone/rclone/releases/download/null/rclone-null-osx-amd64.zip
>     -> [HttpSkipResponseCommand.cc:219] errorCode=3 Resource not found

It seems to be that the error came from here, where for some reason the latest version was determined as null: https://github.com/AnimMouse/setup-rclone/blob/260c6f92c9b33d3fed3452a7d6aeb402c71b9048/scripts/download/macOS.sh#L2

Maybe some additional check/retry logic could be implemented in case the version is not properly returned, to make the run more resilient. 

This step also didn't fail (which it should have), even though it failed to install the tool. Additional check could be implemented for that too.

**Comment by AnimMouse** [comment]
> It seems to be that the error came from here, where for some reason the latest version was determined as null: 
Maybe some additional check/retry logic could be implemented in case the version is not properly returned, to make the run more resilient.

It seems like GitHub APIs goes [down](https://www.githubstatus.com/incidents/tyc8wpsgr2r8) recently, I think if GitHub API goes down, then perhaps we shouldn't be using GitHub Actions, right?

> This step also didn't fail (which it should have), even though it failed to install the tool. Additional check could be implemented for that too.

Thanks for reporting that bug, it seems like I forgot to add `set -e` in the script.

**Comment by zsoltion** [comment]
> It seems like GitHub APIs goes [down](https://www.githubstatus.com/incidents/tyc8wpsgr2r8) recently, I think if GitHub API goes down, then perhaps we shouldn't be using GitHub Actions, right?

Yes, I haven't mentioned it, but the issue happened at 22:35 UTC, and the outage finished at 17:40 UTC, so GitHub was officially fully functional.

**Comment by AnimMouse** [comment]
> the issue happened at 22:35 UTC, and the outage finished at 17:40 UTC, so GitHub was officially fully functional.

With the recent incident on GitHub 3 days in a row due to their mySQL1 load, I think GitHub is still down during that time.

This bug has been solved on 6e5a0cb27f2630afefa0f28fec912bb6b08b4fa7, and this action will now fail when it failed to install the tool. Thanks for your bug report.

**Comment by zsoltion** [comment]
Thank you as well!

**Comment by AnimMouse** [comment]
> where for some reason the latest version was determined as null

#3
