### ISSUE TITLE
Please update the action dependencies

### ISSUE THREAD

**Issue by maksym-fedorov-aura** [AnimMouse/setup-rclone#8]
The warning began to appear while running `AnimMouse/setup-rclone@v1` action:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/cache/restore@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

Thank you in advance

**Comment by AnimMouse** [comment]
Fixed on [v1.8.2](https://github.com/AnimMouse/setup-rclone/releases/tag/v1.8.2)
